remote_theme: daattali/beautiful-jekyll@6.0.1

title: Pages of the Past
author: Nihal Singh
description: A blog exploring interesting moments in history

navbar-links:
  Ancient Rome: "ancient-rome"
  Silk Road: "silk-road"
  World War II: "world-war-2"
  Space Race: "space-race"
  About: "about"

url: "https://nicknack774.github.io"
baseurl: "/history-blog"

plugins:
  - jekyll-remote-theme
