title: Pages of the Past
description: A blog exploring interesting moments in history
baseurl: "/history-blog"
url: "https://nicknack774.github.io"
theme: minima
author: Nihal Singh

header_pages:
  - ancient-rome.md
  - silk-road.md
  - world-war-2.md
  - space-race.md
  - about.md
